language: perl
perl:
  - '5.24'
  - '5.22'
  - '5.20'
  - '5.18'
  - '5.16'
  - '5.14'
  - '5.12'
  - '5.10'
  - '5.8'
addons:
  apt:
    packages:
    - libdb-dev
install:
  - cpanm -nq --installdeps --with-develop .
  - cpanm -nq Carton
script:
  - prove -l --timer t xt
sudo: false
