language: perl
perl:
  - '5.8'
  - '5.10'
  - '5.12'
  - '5.14'
  - '5.16'
  - '5.18'
  - '5.20'
  - '5.22'
  - '5.24'
addons:
  apt:
    packages:
    - libdb-dev
install:
  - cpanm -nq --installdeps --with-develop .
  - cpanm -nq Carton
script:
  - prove --state save -l --timer t xt || { echo '--- retry failed tests ---'; prove --state failed -l --timer; }
sudo: false
