language: perl
perl:
  - '5.8'
  - '5.10'
  - '5.16'
  - '5.26'
addons:
  apt:
    packages:
    - libdb-dev
install:
  - curl -sSL --compressed https://git.io/cpm | perl - install -g --with-develop --with-recommends
script:
  - yath test t xt
sudo: false
